### ISSUE TITLE
Fan Speed Mod

### ISSUE THREAD

**Issue by CIURI86** [airbus-seclab/ilo4_toolbox#17]
Is it possible to make a fan speed mod for the ILO? In the elf.bin there is a Thermal.json file that I think could be modified to allow the temperature thresholds to be modified.

**Comment by alexgzt** [comment]
Hi Ciuri86, 

Just did a quick lookup, the string you mentionned "``Thermal.json``" belongs to the ``.restserver.elf`` module. May be related to:
https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#thermal-redfish-v1-chassis-item-thermal

A fan speed mod may be possible however that is not something we've studied.
