### ISSUE TITLE
Error in inserting backdoor in HPE ILO V 2.40

### ISSUE THREAD

**Issue by abdelrhmanyousri** [airbus-seclab/ilo4_toolbox#19]
Error when trying   

     ./insert_backdoor.sh ilo4_240.bin 

I have downloaded the firmware from [here](https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX_ae600534c9b64bb9a10f0b299c)

       [-] Error, bad file content at offset 1410
       Traceback (most recent call last):
       File "./ilo4_repack.py", line 18, in <module>
       with open(sys.argv[3], "rb") as f:
       IOError: [Errno 2] No such file or directory: 'outdir/elf.bin.patched'

**Comment by alexgzt** [comment]
Hi @abdelrhmanyousri 

Based on the output above, it looks like the file 'outdir/elf.bin.patched' is missing or in the wrong directory.
