### ISSUE TITLE
how to recover symbols

### ISSUE THREAD

**Issue by anotherpk** [airbus-seclab/ilo4_toolbox#28]
Hi, how do you recover the standard library function symbols table or all other symbols?
![image](https://user-images.githubusercontent.com/130426038/231047823-6c371682-1a95-45d7-b2a4-6730477986dd.png)
IDA can't recognize symbols such as `strcmp` `printf`...
Thanks.

**Comment by nikaiw** [comment]
You need to do manual reversing.
