### ISSUE TITLE
iloscan error

### ISSUE THREAD

**Issue by s34lab** [airbus-seclab/ilo4_toolbox#3]
Hello! 
I got an error, when run compiled iloscan (with edited targets: one IP range). 
Error message: 
_panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
         ../iloscan.go:157 +0x2e5_

So line 157 is "_targets := []string{os.Args[1]}_"

What it could be?

**Comment by Sn0rkY** [comment]
Hi, Are you specifying the IP range in CIDR format like this one: 10.0.0.0/24 ?

**Comment by alexgzt** [comment]
Closing inactive issue.
